use_frameworks!

target 'TLRefresh_Example' do
  pod 'TLRefresh', :path => '../'

  target 'TLRefresh_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
